### ISSUE TITLE
support for selecting an object in collector

### ISSUE THREAD

**Issue by kdhl** [Esri/collector-integration#12]
It would be great if one could add a GlobalID (or something similar) to the url and thus open collector with an object selected (point, line or polygon)

**Comment by jakc** [comment]
Related to this enhancement, how about leveraging a &search= parameter, that makes use of the layer level searches setup on Web Maps, to then select the corresponding feature (or return search results to then select from). 

e.g. 
_arcgis-collector://?itemID=35b1ccecf226485ea7d593f100996b49&search=HJ1262_

**Comment by jebu75** [comment]
+1 We would really like this capability as well.  Also to turn on/off layers by parameters.

**Comment by doug-m** [comment]
Thanks for the feedback on this - we've added this to our development road map.

**Comment by DennisWelu** [comment]
+1 This and potentially other options would be great.

**Comment by DennisWelu** [comment]
@doug-m I just noticed the date of your comment about the development road map. Is there any update to the roadmap or features that are not yet documented?

**Comment by doug-m** [comment]
@DennisWelu support for updating an existing feature's attributes is coming in the next release of Collector on iOS. Currently planned for April.

We have made a number of improvements for the new Collector - documented here: https://doc.arcgis.com/en/collector/ipad/help/deploy-map.htm#ESRI_SECTION1_F7DE2402BA8743E5BFC4A1241072960E.

Feel free to log an issue here if there are other enhancements/capabilities you'd like to see.

**Comment by DennisWelu** [comment]
@doug-m Hi Doug, thanks again for the link. I've had a chance to test the search capability in the cited documentation. While the documentation there shows the ability to search for a feature by its Id, I gather that the search-ability is probably affected greatly by the map setup. I've found in my first specific test that the search is more like a _general_ user text search. Instead of finding my feature it did a general search that happen to have 2 Cyrillic search results for places in Kazakhstan. Kind of funny, but not what I was looking for to be sure.

I'd like to be able to say something to the effect of "layer=a&featureId=b" or something like that so that it immediately would center and select that specific feature.

**Comment by doug-m** [comment]
Thanks all for you feedback here - a number of items (search, and updating existing feature have been implemented).  See our [documentation pages](https://doc.arcgis.com/en/collector/ipad/help/deploy-map.htm#ESRI_SECTION1_F7DE2402BA8743E5BFC4A1241072960E) for the latest status.
